AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  CountRepeatedAttributes: false
  Max: 20